### ISSUE TITLE
Colab Cuda upgrade affects xformers and libcudart.so.11.0

### ISSUE THREAD

**Issue by nsarafianos** [camenduru/Wonder3D-colab#8]
Hey @camenduru 

Thanks for putting up this collab. I noticed today that the collab is not working (potentially due to CUDA upgrades). 

* Wonder3D can work if one pip installs the most recent package (cu121 instead of the cu118 one) 
* Instant-nsr throws a "_libcudart.so.11.0: cannot open shared object file: No such file or directory colab_" error which potentially has to do with the tinycudann version that is installed

Happy to get any pointers on how to address this!

**Comment by nsarafianos** [comment]
Solution: 
Installing the latest tinycuda-nn solves this problem (it just takes some time :) ) 

`!pip install ninja git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch`

**Comment by fireincairo00** [comment]
> Solution: Installing the latest tinycuda-nn solves this problem (it just takes some time :) )
> 
> `!pip install ninja git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch`

thanks mate, could not get this to work either, could you provide the exact changes to the notebook to make it work? I got the warning below and the generation fails:

WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.0+cu118 with CUDA 1108 (you have 2.1.0+cu121)
    Python  3.10.13 (you have 3.10.12)

Thanks in advance mate.

**Comment by camenduru** [comment]
thanks for the info ❤ please try again
